
services:

  user-service:
    build: ./services/user-service
    container_name: user_service
    volumes:
      - ./services/user-service:/var/www
    ports:
      - "8001:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql
    networks:
      - app

  appointment-service:
    build: ./services/appointment-service
    container_name: appointment_service
    volumes:
      - ./services/appointment-service:/var/www
    ports:
      - "8002:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - app

  appointment-worker:
    build: ./services/appointment-service
    container_name: appointment_worker
    volumes:
      - ./services/appointment-service:/var/www
    command: php artisan consume:user-events
    restart: unless-stopped
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - app

  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - ./docker/.env
    ports:
      - "3307:3306"
    networks:
      - app
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"   # AMQP port
      - "15673:15672" # Management UI
    env_file:
      - ./docker/.env
    networks:
      - app
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  queue-worker:
    build: ./services/user-service
    container_name: queue_worker
    volumes:
      - ./services/user-service:/var/www
    command: php artisan queue:work database --sleep=3 --tries=3
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - app

networks:
  app:

volumes:
  mysql_data:
  rabbitmq_data: