name: Build, test, and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/user-service
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        # extensions: mbstring, bcmath, pdo_mysql
        # ini-values: post_max_size=256M, upload_max_filesize=256M
        # coverage: none
    # - name: Create database
    #   # run: touch ./database/database.sqlite
    #   run: mysql -e "CREATE DATABASE user_service_test_db;"
    - name: Copy .env 
      run: cp env.test .env
    - name: Install app
      run: composer install
      # run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
    - name: Set DB config for CI
      run: |
        php artisan config:clear
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
    - name: Run migrations
      run: php artisan migrate
      # run: php artisan migrate --env=testing
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse app
    - name: Run tests
      run: vendor/bin/phpunit --configuration phpunit.xml
    
